### ISSUE TITLE
Can't open the pitch pdf

### ISSUE THREAD

**Issue by birkanu** [rerack-me/rerack.me#1]
Hey guys, 

I can't open your pitch pdf, because GitHub thinks it's too big.

**Comment by dsessoms** [comment]
https://www.dropbox.com/s/mtbwbcc99b0jim9/Project%20Pitch.pdf

let me know if that doesn't work

**Comment by dsessoms** [comment]
that was a fail

**Comment by birkanu** [comment]
We've got it now, thank you!
