### ISSUE TITLE
notification number of confirmed games = number to confirm + number pending

### ISSUE THREAD

**Issue by santhoshnarayan** [rerack-me/rerack.me#100]

**Comment by stubailo** [comment]
what does this mean?  what are pending games?

**Comment by santhoshnarayan** [comment]
Games that you can't confirm but need to be confirmed

Like my notification number said 11, there were only 5 I could confirm though, I'm guessing the rest were unconfirmed games but since I wasn't a loser, I couldn't confirm them

—

**Comment by stubailo** [comment]
45a6d6df5a64cf39df2a701d969dea3cf4b43af3 fixed
