### ISSUE TITLE
Rerack emails go to spam for me

### ISSUE THREAD

**Issue by stubailo** [rerack-me/rerack.me#102]
IDK if there's some way to fix this?

**Comment by vpontis** [comment]
I think it's because we've sent so many emails and haven't been interacting with them? IDK. 

We should definitely get this fixed. Maybe using SendGrid on Heroku will help: http://stackoverflow.com/questions/6659446/emails-sent-from-postfix-via-a-rails-app-are-getting-sent-to-spam-in-gmail
