### ISSUE TITLE
if a user signs in and never confirms email they are still part of the system

### ISSUE THREAD

**Issue by dsessoms** [rerack-me/rerack.me#111]
they should be deleted after a certain time

**Comment by stubailo** [comment]
I don't think so - what's the benefit of deleting them?

**Comment by vpontis** [comment]
agreed. lets close this issue.

## 

Victor Pontis
Massachusetts Institute of Technology 2015
vpontis@mit.edu | 858-761-5232

**Comment by dsessoms** [comment]
You will have useless users in the database. This can happen from a user trying to sign in and entering an incorrect email the first time.
