### ISSUE TITLE
Points on details of game

### ISSUE THREAD

**Issue by dsessoms** [rerack-me/rerack.me#116]
Need to add actual points to game details rather than saying points for each

**Comment by vpontis** [comment]
what should they be? the points that were transfered on that game or what?

## 

Victor Pontis
Massachusetts Institute of Technology 2015
vpontis@mit.edu | 858-761-5232

**Comment by dsessoms** [comment]
yeah thats what i would assume. I make that happen real quick

**Comment by dsessoms** [comment]
no longer an issue
