### ISSUE TITLE
Implement typeahead for user input

### ISSUE THREAD

**Issue by stubailo** [rerack-me/rerack.me#15]
https://github.com/twitter/typeahead.js/

**Comment by vpontis** [comment]
This should be fine. Look it over and you can close the issue.

**Comment by stubailo** [comment]
Actually the UX for this still sucks, I feel like when you hit enter it should not submit the form, but select the highlighted suggestion.  We should look into this later

**Comment by stubailo** [comment]
it's good enough at this point for MVP I think
