### ISSUE TITLE
add points transfer to games

### ISSUE THREAD

**Issue by vpontis** [rerack-me/rerack.me#36]
in the game feed it should show how points are transferred from winners to losers. this should also be in the relation table on a player by player basis

**Comment by stubailo** [comment]
Yep this is actually the way it was initially planned in the wireframe, so it's good to have it!

**Comment by stubailo** [comment]
There is room in the page I added to put these in, but IDK how to get them with the new group models

**Comment by vpontis** [comment]
yea, i'm working on groups tonight. when i pull request that hopefully that
will be helpful.

## 

VPontis
