### ISSUE TITLE
add order to player.games

### ISSUE THREAD

**Issue by vpontis** [rerack-me/rerack.me#45]

**Comment by stubailo** [comment]
This might require manually writing a query, because I don't think rails can merge the results of two queries and then order them like that.  I kinda tried, but couldn't get something sane to work

**Comment by vpontis** [comment]
Yea I ran into the same problems 

—
VPontis

**Comment by stubailo** [comment]
Do you want to take this one, I have a lot on my plate with frontend issues

**Comment by vpontis** [comment]
Yea sure 

—
VPontis

**Comment by stubailo** [comment]
Bump

**Comment by vpontis** [comment]
I'm going to work on this tonight and tomorrow. I don't have time until after chapter meeting because I need to do this 8.05 pset. Sorry but I'll be working soon. 

—
VPontis

**Comment by stubailo** [comment]
@dsessoms can you crack this?  Now it's even harder cause we only want confirmed games to show up on the profile/game feed right?

**Comment by dsessoms** [comment]
we want to order games on created_at correct?

**Comment by stubailo** [comment]
Yep
