### ISSUE TITLE
Add pagination to game feed and ranking page

### ISSUE THREAD

**Issue by stubailo** [rerack-me/rerack.me#53]

**Comment by dsessoms** [comment]
still trying to do this?

**Comment by stubailo** [comment]
Yeah we still want this I think

**Comment by vpontis** [comment]
ill do this now

**Comment by vpontis** [comment]
i pushed something for rankings here https://github.com/6170-fa13/vpontis_stubailo_dsessoms_santhoshnarayan_final/tree/feature_paginate

we still need to figure out how we want to display the game feed before we paginate it
