### ISSUE TITLE
add ranking and points to groups

### ISSUE THREAD

**Issue by vpontis** [rerack-me/rerack.me#66]

**Comment by vpontis** [comment]
how do you guys think we should do this? @stubailo @dsessoms

**Comment by dsessoms** [comment]
little late, but I like how you have the group_players table. We are not planning on adding games that were created before the group was created but contain only members from that group, correct? As long as that is the case, I feel like updating the points will be very similar to the current system but we can just add one more check to see if all the members are in the same group, and if so update their group_player's points.

**Comment by vpontis** [comment]
Actually we said that we were going to include games that were created before the group. So that means whenever a player is added to the group, we need to recalculate group rankings. 

This may be something we should think about. @stubailo 

I think we can do two things: include all games for that subset of players and recalculate rankings when players enter or leave a group; or we can create a group then when any game is created, apply that game to all relevant groups. What do we want to do? I think there are advantages to each.
