### ISSUE TITLE
make sure that player usernames don't have puncutation

### ISSUE THREAD

**Issue by vpontis** [rerack-me/rerack.me#68]
you will also need to change the rake task. i think spaces are actually fine. let me know what you guys think.

**Comment by stubailo** [comment]
What's wrong with punctuation?

**Comment by vpontis** [comment]
it breaks the player urls

## 

VPontis

**Comment by stubailo** [comment]
I feel like we should be able to just escape/unescape the urls as necessary.

http://ruby-doc.org/stdlib-1.9.3/libdoc/uri/rdoc/URI/Escape.html

Although, if we restrict the characters possible in a username we can prevent things like ︻╦╤─ Ϩ∆ϨῌKØ ─╤╦︻

**Comment by vpontis** [comment]
so which do we want to do? restrict or escape?

## 

VPontis

**Comment by stubailo** [comment]
I think we should restrict it.  Allowing people to have arbitrary characters can make life complicated.

**Comment by vpontis** [comment]
yea i agree. lets do letters, underscores, numbers, and spaces? or no
spaces?

## 

VPontis

**Comment by stubailo** [comment]
http://tools.ietf.org/html/rfc3986#section-2.3

Characters allowed in urls without escaping are:
ALPHA / DIGIT / "-" / "." / "_" / "~"

I think it would be tight to allow brackets and parens and spaces stuff though.  Like in a lot of games people specify their clan with brackets like:
[PSK] sashko
PSK`sashko

What about just allowing any ASCII characters?  so like nothing like ╦ but maybe ~!@#$%^&*()_+ is fine?

I like that option the most.  Basically allow any character that is "reasonable" from a readability point of view.  What do you think?

**Comment by vpontis** [comment]
Hmm I know it breaks on . though because it thinks whatever comes after the period is going to be the content specifier. Like HTML or Json or whatever. 

—
VPontis

**Comment by stubailo** [comment]
yeah just like use string.parametrize or something?

**Comment by vpontis** [comment]
yea that looks cool. so lets use parametrize and allow ascii characters. is
that our final decision?

## 

VPontis

**Comment by stubailo** [comment]
Sounds good to me!  We just need to make sure that the parametrized form is
unique

**Comment by vpontis** [comment]
hmm yea, i think it will be unique if we do not allow the parameter to
appear in usernames. i'm not sure how to do it otherwise, though im sure
there is a method for it.

## 

VPontis

**Comment by stubailo** [comment]
Make a new field called parameterized username and make that one unique

**Comment by vpontis** [comment]
Duh. Yea ok seeeet. 

—
VPontis
