### ISSUE TITLE
your ranking should not include unranked players

### ISSUE THREAD

**Issue by vpontis** [rerack-me/rerack.me#96]

**Comment by stubailo** [comment]
#return ranking of player based on algorithm
  def ranking
    Player.where("points > ? AND username != ?", points, self.username).count + 1
  end

currently ranking is like this so it needs to be entirely switched to use group rankings anyway.  thoughts?

**Comment by vpontis** [comment]
Umm no I think global ranking should still work like this. I think it should be:

players = Player.order('points DESC')
players = players.reject {|p| p.games_count < 2}
ranking = players.index_of(self)

What do you think?

**Comment by vpontis** [comment]
#108 should fix
